### ISSUE TITLE
Start Portfolio Module

### ISSUE THREAD

**Issue by ShaunCYFSA** [CodeYourFuture/CYFZA-staff_tickets#1]
Porfolio module notes and updates

**Comment by ShaunCYFSA** [comment]
Portfolio module notes here.
Portfolio overview [here](https://docs.google.com/document/d/1Dr0BI0UivD-N2m-HLxiDP71VvdFNIt4NzDSOqGaPppY/edit#heading=h.tpwpnh51th3ll)

Portfolio graduate project [tracker](https://docs.google.com/spreadsheets/d/1j9cXvpZ-f17YcgJYBJqGJeDt-cffqcUWiTdRkojCa6c/edit#gid=27835831)

Module will kick off once projects are visible.

**Comment by ShaunCYFSA** [comment]
Update 13/11/2023

1 project group added to the tracker
1 volunteer ready to assist

**Comment by SallyMcGrath** [comment]
I think this is a milestone, not a ticket
