### ISSUE TITLE
Add class slots to Class Planner for ITP

### ISSUE THREAD

**Issue by ShaunCYFSA** [CodeYourFuture/CYFZA-staff_tickets#132]
### Background

Make it easier to track and manage volunteers who sign up for the Saturday drop-in sessions to assist trainees.

### Acceptance criteria

Create slots with corresponding sprints of the syllabus attached.

### Owner

N/A

### Stakeholder

CYF SA management team

### Approver

CYF SA management team

**Comment by SallyMcGrath** [comment]
Maybe we can ask classplanner to populate this for the next year for all regions as we know the dates

**Comment by ShaunCYFSA** [comment]
Great suggestion.
I am happy to add the dates for now.
