### ISSUE TITLE
Look for Venue for ZA DLP 2

### ISSUE THREAD

**Issue by ShaunCYFSA** [CodeYourFuture/CYFZA-staff_tickets#27]
Looking for venue for ZA DLP 2

**Comment by ShaunCYFSA** [comment]
Requirements:-
Venue
New group
Launch date
Update course material

**Comment by MattCFry** [comment]
Is this a ticket or milestone?

**Comment by SallyMcGrath** [comment]
If you're working on this ticket, put your face on it, @ShaunCYFSA

**Comment by ShaunCYFSA** [comment]
@SallyMcGrath - I updated my profile.

**Comment by ShaunCYFSA** [comment]
Mustadafin to host CYF SA DLP 2 classes starting 2 March and ending on 16 March.
