### ISSUE TITLE
ZA DLP Implimentation

### ISSUE THREAD

**Issue by ShaunCYFSA** [CodeYourFuture/CYFZA-staff_tickets#3]

**Comment by ShaunCYFSA** [comment]
Tracking implementation of DLP rollout.

Linking up with Amy to launch.

Review Week 1 coursework material
10/10/2023
Review Week 2 coursework material
17/10/2023
Review Week 2/3 coursework material.
24/10/2023
Review Week 3 coursework material.
31/10/2023
Training with Amy for DLP coursework weeks 1/ 2 
07/11/2023
Training with Amy for DLP coursework weeks 2 /3
15/11/2023
Plan first DLP class for 25/11/2023
21/11/2023
Run first DLP session at Beth Uriel
25/11/2023

**Comment by SallyMcGrath** [comment]
I think these are milestones, and it also looks completed.
