### ISSUE TITLE
Run graduate session on 13 March

### ISSUE THREAD

**Issue by ShaunCYFSA** [CodeYourFuture/CYFZA-staff_tickets#43]
Background
Set up a call with graduates. The guest speaker was invited to share the CYF journey with graduates.

Acceptance criteria
Guest speaker invited
Graduates invited
Volunteers invited
Zoom call set up.

Owner
N/A

Stakeholder
Volunteers/graduates

Approver
Lana Franks

**Comment by SallyMcGrath** [comment]
This is now in the past, so moving to backlog and marking as blocked

**Comment by ShaunCYFSA** [comment]
I've moved the session over to done.
The graduate session was successfully run.
